logging:
  level:
    za:
      co:
        binarylabs:
          todoapp: INFO
spring:
  application:
    name: Todo
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      poolName: Hikari
    password: ''
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/todo
    username: todo
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
